/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CaixaSchema extends BaseModel {
  static $columns = ['createdAt', 'dataFecho', 'deletedAt', 'id', 'observacoes', 'posId', 'status', 'totalCaixa', 'totalVendas', 'updatedAt', 'userId', 'valorInicial'] as const
  $columns = CaixaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dataFecho: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare observacoes: string | null
  @column()
  declare posId: string | null
  @column()
  declare status: string | null
  @column()
  declare totalCaixa: string | null
  @column()
  declare totalVendas: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
  @column()
  declare valorInicial: string | null
}

export class CategoriasProdutoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'produtoCategoriaId', 'produtoId', 'updatedAt'] as const
  $columns = CategoriasProdutoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare produtoCategoriaId: string | null
  @column()
  declare produtoId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ClienteSchema extends BaseModel {
  static $columns = ['ativo', 'bairro', 'cidade', 'clientePaiId', 'codigoPostal', 'createdAt', 'dataNascimento', 'deletedAt', 'email', 'empresaId', 'endereco', 'estadoCivil', 'foto', 'genero', 'id', 'limiteCredito', 'logo', 'nif', 'nome', 'numeroRegistro', 'observacao', 'pais', 'profissao', 'provincia', 'razaoSocial', 'saldo', 'telefone', 'telefoneSecundario', 'tipo', 'updatedAt', 'website'] as const
  $columns = ClienteSchema.$columns
  @column()
  declare ativo: boolean | null
  @column()
  declare bairro: string | null
  @column()
  declare cidade: string | null
  @column()
  declare clientePaiId: string | null
  @column()
  declare codigoPostal: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dataNascimento: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare empresaId: string | null
  @column()
  declare endereco: string | null
  @column()
  declare estadoCivil: string | null
  @column()
  declare foto: string | null
  @column()
  declare genero: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare limiteCredito: string | null
  @column()
  declare logo: string | null
  @column()
  declare nif: string | null
  @column()
  declare nome: string | null
  @column()
  declare numeroRegistro: string | null
  @column()
  declare observacao: string | null
  @column()
  declare pais: string | null
  @column()
  declare profissao: string | null
  @column()
  declare provincia: string | null
  @column()
  declare razaoSocial: string | null
  @column()
  declare saldo: string | null
  @column()
  declare telefone: string | null
  @column()
  declare telefoneSecundario: string | null
  @column()
  declare tipo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare website: string | null
}

export class CobrancaSchema extends BaseModel {
  static $columns = ['createdAt', 'dataVencimento', 'deletedAt', 'id', 'moeda', 'pago', 'referencia', 'status', 'subscricaoId', 'updatedAt', 'valor'] as const
  $columns = CobrancaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dataVencimento: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare moeda: string | null
  @column()
  declare pago: boolean | null
  @column()
  declare referencia: string | null
  @column()
  declare status: string | null
  @column()
  declare subscricaoId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare valor: string | null
}

export class CupomSchema extends BaseModel {
  static $columns = ['codigo', 'createdAt', 'deletedAt', 'desconto', 'empresaId', 'id', 'promotorId', 'updatedAt', 'userId', 'validade'] as const
  $columns = CupomSchema.$columns
  @column()
  declare codigo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare desconto: string | null
  @column()
  declare empresaId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare promotorId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
  @column.dateTime()
  declare validade: DateTime | null
}

export class EmpresaSchema extends BaseModel {
  static $columns = ['companyAlias', 'contacto', 'createdAt', 'deletedAt', 'id', 'inadiplente', 'localizacao', 'nif', 'nome', 'regimeIva', 'status', 'tamanho', 'updatedAt', 'userId', 'verified'] as const
  $columns = EmpresaSchema.$columns
  @column()
  declare companyAlias: string | null
  @column()
  declare contacto: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inadiplente: boolean | null
  @column()
  declare localizacao: string | null
  @column()
  declare nif: string | null
  @column()
  declare nome: string | null
  @column()
  declare regimeIva: boolean | null
  @column()
  declare status: boolean | null
  @column()
  declare tamanho: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
  @column()
  declare verified: boolean | null
}

export class EmpresaContaBancariaSchema extends BaseModel {
  static $columns = ['conta', 'createdAt', 'deletedAt', 'empresaId', 'iban', 'id', 'updatedAt'] as const
  $columns = EmpresaContaBancariaSchema.$columns
  @column()
  declare conta: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare empresaId: string | null
  @column()
  declare iban: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EstoqueSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'loteProdutoId', 'motivo', 'posId', 'produtoId', 'quantidade', 'registradoPor', 'tipoMovimentacao', 'updatedAt'] as const
  $columns = EstoqueSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare loteProdutoId: string | null
  @column()
  declare motivo: string | null
  @column()
  declare posId: string | null
  @column()
  declare produtoId: string | null
  @column()
  declare quantidade: number | null
  @column()
  declare registradoPor: string | null
  @column()
  declare tipoMovimentacao: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FacturaSchema extends BaseModel {
  static $columns = ['clienteNif', 'clienteNome', 'createdAt', 'dataEmissao', 'deletedAt', 'empresaId', 'id', 'numero', 'observacoes', 'status', 'tipo', 'total', 'updatedAt', 'vendaId'] as const
  $columns = FacturaSchema.$columns
  @column()
  declare clienteNif: string | null
  @column()
  declare clienteNome: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dataEmissao: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare empresaId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare numero: number
  @column()
  declare observacoes: string | null
  @column()
  declare status: string
  @column()
  declare tipo: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vendaId: string
}

export class LeadSchema extends BaseModel {
  static $columns = ['createdAt', 'empresaId', 'id', 'promotorId', 'updatedAt'] as const
  $columns = LeadSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare empresaId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare promotorId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LoteProdutoSchema extends BaseModel {
  static $columns = ['createdAt', 'dataFabrico', 'dataValidade', 'deletedAt', 'id', 'lote', 'precoCompra', 'precoVenda', 'produtoId', 'quantidadeEmEstoque', 'updatedAt'] as const
  $columns = LoteProdutoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dataFabrico: DateTime | null
  @column.date()
  declare dataValidade: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lote: string | null
  @column()
  declare precoCompra: string | null
  @column()
  declare precoVenda: string | null
  @column()
  declare produtoId: string | null
  @column()
  declare quantidadeEmEstoque: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MarcaSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'empresaId', 'id', 'nome', 'updatedAt'] as const
  $columns = MarcaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column()
  declare empresaId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MetodopagamentoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'id', 'nome', 'updatedAt'] as const
  $columns = MetodopagamentoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PapelSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'id', 'nome', 'updatedAt'] as const
  $columns = PapelSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PapelPermissaoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'papelId', 'permissaoId', 'updatedAt'] as const
  $columns = PapelPermissaoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare papelId: string | null
  @column()
  declare permissaoId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PermissaoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'id', 'nome', 'updatedAt'] as const
  $columns = PermissaoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PessoaSchema extends BaseModel {
  static $columns = ['cidade', 'createdAt', 'dataNascimento', 'deletedAt', 'email', 'empresaId', 'endereco', 'genero', 'id', 'imgUrl', 'nif', 'nome', 'pais', 'sobrenome', 'telefone', 'tipo', 'updatedAt', 'userId'] as const
  $columns = PessoaSchema.$columns
  @column()
  declare cidade: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dataNascimento: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare empresaId: string | null
  @column()
  declare endereco: string | null
  @column()
  declare genero: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imgUrl: string | null
  @column()
  declare nif: string | null
  @column()
  declare nome: string | null
  @column()
  declare pais: string | null
  @column()
  declare sobrenome: string | null
  @column()
  declare telefone: string | null
  @column()
  declare tipo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
}

export class PlanoSchema extends BaseModel {
  static $columns = ['ativo', 'createdAt', 'deletedAt', 'descricao', 'id', 'limiteUso', 'moeda', 'nome', 'periodo', 'preco', 'updatedAt'] as const
  $columns = PlanoSchema.$columns
  @column()
  declare ativo: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare limiteUso: string | null
  @column()
  declare moeda: string | null
  @column()
  declare nome: string | null
  @column()
  declare periodo: string | null
  @column()
  declare preco: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PoSchema extends BaseModel {
  static $columns = ['contacto', 'createdAt', 'deletedAt', 'email', 'empresaId', 'id', 'localizacao', 'nome', 'updatedAt'] as const
  $columns = PoSchema.$columns
  @column()
  declare contacto: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare empresaId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare localizacao: string | null
  @column()
  declare nome: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutoCategoriaSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'empresaId', 'id', 'nome', 'updatedAt'] as const
  $columns = ProdutoCategoriaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column()
  declare empresaId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutoContraindicacoeSchema extends BaseModel {
  static $columns = ['contraindicacao', 'createdAt', 'deletedAt', 'id', 'produtoId', 'updatedAt'] as const
  $columns = ProdutoContraindicacoeSchema.$columns
  @column()
  declare contraindicacao: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare produtoId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutoDescricaoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricaoDetalhada', 'id', 'produtoId', 'propriedade', 'updatedAt'] as const
  $columns = ProdutoDescricaoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricaoDetalhada: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare produtoId: string | null
  @column()
  declare propriedade: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutoFabricanteSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'empresaId', 'endereco', 'id', 'nome', 'telefone', 'updatedAt'] as const
  $columns = ProdutoFabricanteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare empresaId: string | null
  @column()
  declare endereco: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string | null
  @column()
  declare telefone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutoFormatoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'empresaId', 'id', 'nome', 'updatedAt'] as const
  $columns = ProdutoFormatoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column()
  declare empresaId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutoFornecedoreSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'empresaId', 'endereco', 'id', 'nome', 'telefone', 'updatedAt'] as const
  $columns = ProdutoFornecedoreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare empresaId: string | null
  @column()
  declare endereco: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string | null
  @column()
  declare telefone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutoMediaSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'media', 'produtoId', 'updatedAt'] as const
  $columns = ProdutoMediaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare media: string | null
  @column()
  declare produtoId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutoRecomendacoeSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'produtoId', 'recomendacao', 'updatedAt'] as const
  $columns = ProdutoRecomendacoeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare produtoId: string | null
  @column()
  declare recomendacao: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'empresaId', 'fabricanteId', 'formatoId', 'fornecedorId', 'id', 'isService', 'marcaId', 'nome', 'updatedAt'] as const
  $columns = ProdutoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column()
  declare empresaId: string | null
  @column()
  declare fabricanteId: string | null
  @column()
  declare formatoId: string | null
  @column()
  declare fornecedorId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isService: boolean | null
  @column()
  declare marcaId: string | null
  @column()
  declare nome: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProdutosReembolsoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'quantidade', 'updatedAt', 'userId', 'vendaItemId'] as const
  $columns = ProdutosReembolsoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare quantidade: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
  @column()
  declare vendaItemId: string | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'id', 'nome', 'updatedAt', 'userId'] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
}

export class ProjectPermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'id', 'name', 'projectId', 'updatedAt'] as const
  $columns = ProjectPermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare projectId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectPermissionRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'projectPermissionId', 'projectRoleId', 'updatedAt'] as const
  $columns = ProjectPermissionRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare projectPermissionId: string | null
  @column()
  declare projectRoleId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'descricao', 'id', 'name', 'projectId', 'updatedAt'] as const
  $columns = ProjectRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare descricao: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare projectId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectUserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'id', 'password', 'projectId', 'updatedAt', 'username'] as const
  $columns = ProjectUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare projectId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string | null
}

export class ProjectUserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'projectRoleId', 'projectUserId', 'updatedAt'] as const
  $columns = ProjectUserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare projectRoleId: string | null
  @column()
  declare projectUserId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PromotorSchema extends BaseModel {
  static $columns = ['ativo', 'codigoPerfil', 'createdAt', 'deletedAt', 'email', 'empresaId', 'id', 'nome', 'telefone', 'updatedAt'] as const
  $columns = PromotorSchema.$columns
  @column()
  declare ativo: boolean
  @column()
  declare codigoPerfil: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare empresaId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string
  @column()
  declare telefone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PromotorAccessTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'promotorId', 'tokenHash', 'updatedAt'] as const
  $columns = PromotorAccessTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare promotorId: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PromotorOtpSchema extends BaseModel {
  static $columns = ['codigoHash', 'createdAt', 'expiresAt', 'id', 'promotorId', 'updatedAt', 'usedAt'] as const
  $columns = PromotorOtpSchema.$columns
  @column()
  declare codigoHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare promotorId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class SubscricaoSchema extends BaseModel {
  static $columns = ['canceladaEm', 'clienteId', 'createdAt', 'dataFim', 'dataInicio', 'deletedAt', 'id', 'planoId', 'renova', 'status', 'updatedAt'] as const
  $columns = SubscricaoSchema.$columns
  @column.date()
  declare canceladaEm: DateTime | null
  @column()
  declare clienteId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dataFim: DateTime | null
  @column.date()
  declare dataInicio: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare planoId: string | null
  @column()
  declare renova: boolean | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'empresaId', 'id', 'password', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare empresaId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}

export class UserPapelSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'papelId', 'updatedAt', 'userId'] as const
  $columns = UserPapelSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare papelId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
}

export class UserpoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'posId', 'updatedAt', 'userId'] as const
  $columns = UserpoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare posId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
}

export class VendaItenSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'desconto', 'id', 'loteProdutoId', 'precoUnitario', 'quantidade', 'quantidadeReembolsada', 'reembolsado', 'total', 'updatedAt', 'vendaId'] as const
  $columns = VendaItenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare desconto: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare loteProdutoId: string
  @column()
  declare precoUnitario: string
  @column()
  declare quantidade: number
  @column()
  declare quantidadeReembolsada: number
  @column()
  declare reembolsado: boolean
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vendaId: string
}

export class VendapagamentoSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'metodoPagamentoId', 'updatedAt', 'valor', 'vendaId'] as const
  $columns = VendapagamentoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metodoPagamentoId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare valor: string | null
  @column()
  declare vendaId: string | null
}

export class VendaSchema extends BaseModel {
  static $columns = ['caixaId', 'clienteOnlineId', 'clientePresencialId', 'createdAt', 'cupomId', 'deletedAt', 'id', 'motivoCancelamento', 'motivoReembolso', 'status', 'total', 'updatedAt', 'valorDesconto', 'vendaTipo'] as const
  $columns = VendaSchema.$columns
  @column()
  declare caixaId: string | null
  @column()
  declare clienteOnlineId: string | null
  @column()
  declare clientePresencialId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cupomId: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare motivoCancelamento: string | null
  @column()
  declare motivoReembolso: string | null
  @column()
  declare status: string | null
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare valorDesconto: string
  @column()
  declare vendaTipo: string | null
}

export class VerificationTokenHashSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'empresaId', 'id', 'purpose', 'updatedAt', 'userId', 'verificationTokenExpiresAt', 'verificationTokenHash', 'verificationTokenPublic', 'verified'] as const
  $columns = VerificationTokenHashSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare empresaId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare purpose: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
  @column.dateTime()
  declare verificationTokenExpiresAt: DateTime | null
  @column()
  declare verificationTokenHash: string | null
  @column()
  declare verificationTokenPublic: string | null
  @column()
  declare verified: boolean | null
}
