export interface CreateclienteDTO {
  cliente_pai_id?: string
  foto?: string
  logo?: string
  observacao?: string
  saldo?: number
  limite_credito?: number
  ativo?: boolean
  codigo_postal?: string
  pais?: string
  provincia?: string
  cidade?: string
  bairro?: string
  endereco?: string
  website?: string
  profissao?: string
  estado_civil?: string
  genero?: string
  data_nascimento?: Date
  numero_registro?: string
  nif?: string
  telefone_secundario?: string
  telefone?: string
  email?: string
  razao_social?: string
  nome_fantasia?: string
  nome?: string
  tipo: string
}
export interface UpdateclienteDTO {
  cliente_pai_id?: string
  foto?: string
  logo?: string
  observacao?: string
  saldo?: number
  limite_credito?: number
  ativo?: boolean
  codigo_postal?: string
  pais?: string
  provincia?: string
  cidade?: string
  bairro?: string
  endereco?: string
  website?: string
  profissao?: string
  estado_civil?: string
  genero?: string
  data_nascimento?: Date
  numero_registro?: string
  nif?: string
  telefone_secundario?: string
  telefone?: string
  email?: string
  razao_social?: string
  nome_fantasia?: string
  nome?: string
  tipo?: string
}
