import vine, { SimpleMessagesProvider } from "@vinejs/vine"

export const messages = {
    'string': 'O campo {{ field }} deve ser uma string',
    'email': 'O campo {{ field }} deve ser um endereço de email válido',
    'regex': 'O formato do campo {{ field }} é inválido',
    'url': 'O campo {{ field }} deve ser uma URL válida',
    'activeUrl': 'O campo {{ field }} deve ser uma URL válida',
    'alpha': 'O campo {{ field }} deve conter apenas letras',
    'alphaNumeric': 'O campo {{ field }} deve conter apenas letras e números',
    'minLength': 'O campo {{ field }} deve ter pelo menos {{ min }} caracteres',
    'maxLength': 'O campo {{ field }} não deve ter mais que {{ max }} caracteres',
    'fixedLength': 'O campo {{ field }} deve ter {{ size }} caracteres',
    'confirmed': 'Os campos {{ field }} e {{ otherField }} devem ser iguais',
    'endsWith': 'O campo {{ field }} deve terminar com {{ substring }}',
    'startsWith': 'O campo {{ field }} deve começar com {{ substring }}',
    'sameAs': 'Os campos {{ field }} e {{ otherField }} devem ser iguais',
    'notSameAs': 'Os campos {{ field }} e {{ otherField }} devem ser diferentes',
    'in': 'O campo {{ field }} selecionado é inválido',
    'notIn': 'O campo {{ field }} selecionado é inválido',
    'ipAddress': 'O campo {{ field }} deve ser um endereço IP válido',
    'uuid': 'O campo {{ field }} deve ser um UUID válido',
    'ascii': 'O campo {{ field }} deve conter apenas caracteres ASCII',
    'creditCard': 'O campo {{ field }} deve ser um número de cartão de {{ providersList }} válido',
    'hexCode': 'O campo {{ field }} deve ser um código de cor hexadecimal válido',
    'iban': 'O campo {{ field }} deve ser um número IBAN válido',
    'jwt': 'O campo {{ field }} deve ser um token JWT válido',
    'coordinates': 'O campo {{ field }} deve conter coordenadas de latitude e longitude',
    'mobile': 'O campo {{ field }} deve ser um número de telefone móvel válido',
    'passport': 'O campo {{ field }} deve ser um número de passaporte válido',
    'postalCode': 'O campo {{ field }} deve ser um código postal válido',
    'number': 'O campo {{ field }} deve ser um número',
    'min': 'O campo {{ field }} deve ser pelo menos {{ min }}',
    'max': 'O campo {{ field }} não deve ser maior que {{ max }}',
    'range': 'O campo {{ field }} deve estar entre {{ min }} e {{ max }}',
    'positive': 'O campo {{ field }} deve ser positivo',
    'negative': 'O campo {{ field }} deve ser negativo',
    'decimal': 'O campo {{ field }} deve ter {{ digits }} casas decimais',
    'withoutDecimals': 'O campo {{ field }} não deve ter casas decimais',
    'date': 'O campo {{ field }} deve ser um valor de data e hora',
    'date.equals': 'O campo {{ field }} deve ser uma data igual a {{ expectedValue }}',
    'date.after': 'O campo {{ field }} deve ser uma data após {{ expectedValue }}',
    'date.before': 'O campo {{ field }} deve ser uma data antes de {{ expectedValue }}',
    'date.afterOrEqual': 'O campo {{ field }} deve ser uma data igual ou após {{ expectedValue }}',
    'date.beforeOrEqual':'O campo {{ field }} deve ser uma data igual ou antes de {{ expectedValue }}',
    'date.sameAs': 'Os campos {{ field }} e {{ otherField }} devem ser iguais',
    'date.notSameAs': 'Os campos {{ field }} e {{ otherField }} devem ser diferentes',
    'date.afterField': 'O campo {{ field }} deve ser uma data após {{ otherField }}',
    'unique': '{{field}} já existe',
    'exists': '{{field}} não existe',
    'required': '{{field}} é obrigatório',
}

vine.messagesProvider = new SimpleMessagesProvider(messages)